### ISSUE TITLE
Test_DTALite_0922_2015

### ISSUE THREAD

**Issue by TonyLiu2015** [xzhou99/dtalite_beta_test#1]
1. There is no output for observed link count and simulated link count in output_validation_result.csv, but it has the simulated link count over observed link count. It means that those values have been recorded, but they are not output.

2. Can you close the output of internal_routing_policy_minxxx.csv files? For a large-scale network, it is time-consuming and currently it is unnecessary.

**Comment by rayman021** [comment]
1. This small bug will be solved in the latest version. Observed link count and simulated link count will be output in the "output_validation_result.csv" file.

2. In the latest version, the "internal_routing_policy_minxxx.csv" has been renamed as "RT_input/output_routing_policy_xxhxxmxxs.csv", and the input/output frequency is controlled by "DTASettings.txt" file. Setting the parameters as follows,
-----------------------------------------------------------------------------
[ABM_integration]
RT_Input_Routing_Policy_Frequency_in_Seconds=0
RT_Output_Routing_Policy_Frequency_in_Seconds=0
-----------------------------------------------------------------------------
Then, the files are not been output.
